[package]
name = "dom-hacking"
version = "0.1.0"
authors = ["Dana Keeler <mozkeeler@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
rand = "0.7"
whois-rust = "1.1.9"
